### ISSUE TITLE
Consider changing project name

### ISSUE THREAD

**Issue by virtix** [cfpb/devdash#15]
In the context of recent a presentation, the open-source-wizard project name evoked expectations of a literal person. In order to avoid confusion in the future and increase adoption, perhaps, it might make sense to change the project name to that of a real wizard?

![gandalf-shakes-head](https://cloud.githubusercontent.com/assets/12570/4768755/67f72192-5b6f-11e4-81aa-2926cbbd2fb1.gif)

Ref:
<blockquote class="twitter-tweet" lang="en"><p><a href="https://twitter.com/virtix">@virtix</a> <a href="https://twitter.com/BenBalter">@BenBalter</a> when I saw it on the diagram I assumed it would be a literal person with, to some extent, magic powers</p>&mdash; Nick Mapmeld (@mapmeld) <a href="https://twitter.com/mapmeld/status/525463473011318785">October 24, 2014</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by dgreisen-cfpb** [comment]
We are going with the much less fun, but hopefully more descriptive 'devdash'. However, our authorization management microservice has now been broken out and is called Kratos, one of Zeus's winged enforcers. https://github.com/cfpb/kratos.
