### ISSUE TITLE
need indication that a request is pending

### ISSUE THREAD

**Issue by dgreisen-cfpb** [cfpb/devdash#35]
This is particularly important now that creating a asset (repo) is synchronous.

**Comment by himedlooff** [comment]
https://github.com/cfpb/open-source-wizard/pull/37 addresses this for assets, but not for users. Do we need something for adding users as well?

**Comment by dgreisen-cfpb** [comment]
I don't think so - if we get feedback that it is needed we can open a new issue. assets are the only api request that are synchronous. All others the heaving lifting is performed by a background worker.
